spring:
  jpa:
    properties:
      hibernate:
        generate_statistics: true
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/lms_db
    username: root
    password: root

logging:
  level:
    'com.amalvadkar.lms' : debug
    'org.hibernate.stat' : debug
    'org.hibernate.SQL' : debug
    'org.hibernate.orm.jdbc.bind' : trace

lms:
  emailSendEnabled: true
  app-url: http://localhost:4200