spring :
 mail:
   host: ${EMAIL_HOST}
   username: ${EMAIL_ID}
   password: ${APP_PASSWORD}
   port: ${EMAIL_PORT}
   protocol: ${EMAIL_PROTOCOL}
   test-connection: false
   properties:
     mail:
       smtp:
         auth: true
         starttls:
           enable: true
 jpa:
  open-in-view: false
 application:
    name: lms-service-auth
 thymeleaf:
   check-template-location: false

server:
  port: 9091



lms:
  otpLength: 6
  otpExpiryDurationInMin: 20
  jwt-secret: ${JWT_SECRET}
  jwtExpiryTimeInSec: 3600 # 1 hour
  email-templates-location: classpath:/email-templates/